module.exports = {
	items: [
		{ full_name: 'slammayjammay/dotfiles' },
		{ full_name: 'vim/vim' },
		{ full_name: 'ma6174/vim' },
		{ full_name: 'VSCodeVim/Vim' },
		{ full_name: 'amix/vimrc' },
		{ full_name: 'spf13/spf13-vim' },
		{ full_name: 'philc/vimium' },
		{ full_name: 'dracula/vim' },
		{ full_name: 'SpaceVim/SpaceVim' },
		{ full_name: 'VundleVim/Vundle.vim' },
		{ full_name: 'yangyangwithgnu/use_vim_as_ide' },
		{ full_name: 'carlhuda/janus' },
		{ full_name: 'junegunn/vim-plug' },
		{ full_name: 'wklken/k-vim' },
		{ full_name: 'skywind3000/vim' },
		{ full_name: 'fatih/vim-go' },
		{ full_name: 'tpope/vim-pathogen' },
		{ full_name: 'tao12345666333/vim' },
		{ full_name: 'neovim/neovim' },
		{ full_name: 'vim-airline/vim-airline' },
		{ full_name: 'chxuan/vimplus' },
		{ full_name: 'honza/vim-snippets' },
		{ full_name: 'tpope/vim-fugitive' },
		{ full_name: 'ycm-core/YouCompleteMe' },
		{ full_name: 'vimwiki/vimwiki' },
		{ full_name: 'vim-syntastic/syntastic' },
		{ full_name: 'altercation/vim-colors-solarized' },
		{ full_name: 'tomasr/molokai' },
		{ full_name: 'syl20bnr/spacemacs' },
		{ full_name: 'wsdjeg/vim-galore-zh_cn' },
		{ full_name: 'dofy/learn-vim' }
	]
};
